【問題4-1】

In [1]:
def AND(x1, x2):
    ######以下にコードを書いて下さい######
    w1, w2, theta = 0.3, 0.3, 0.4
    ######「tmp」に「x1w1 + x2w2」を代入して下さい######
    tmp = x1*w1 + x2*w2
    ######「tmp」の値で条件分岐し「０」か「１」を返して下さい######
    if tmp > theta:
        return 1
    elif tmp <= theta:
        return 0
        
        
y1 = AND(0, 0)
y2 = AND(0, 1)
y3 = AND(1, 0)
y4 = AND(1, 1)
print(y1, y2, y3, y4)
######「shift + Enter」キーを押して下さい######

0 0 0 1


【問題4-2】

In [6]:
import numpy as np
def AND(x1, x2):
    #######「x」と「w」に配列を代入して下さい######
    x = np.array([x1, x2])
    w = np.array([0.3, 0.3])
    ######「b」にバイアスを代入して下さい######
    b = -0.4
    ######「tmp」に「x1w1 + x2w2 + b」を代入して下さい######
    tmp = np.sum(x*w) + b
    ######「tmp」の値で条件分けし「０」か「１」を返して下さい######
    if tmp > 0:
        return 1
    else:
        return 0
    
y1 = AND(0, 0)
y2 = AND(0, 1)
y3 = AND(1, 0)
y4 = AND(1, 1)
print(y1, y2, y3, y4)
######「shift + Enter」キーを押して下さい######

0 0 0 1


【問題4-3】

In [7]:
def NAND(x1, x2):
    ######以下にコードを書いて下さい######
    x = np.array([x1, x2])
    w = np.array([-0.3, -0.3])
    b = 0.4
    tmp = np.sum(x*w) + b
    if tmp > 0:
        return 1
    else:
        return 0
    
    
y1 = NAND(0, 0)
y2 = NAND(0, 1)
y3 = NAND(1, 0)
y4 = NAND(1, 1)
print(y1, y2, y3, y4)
######「shift + Enter」キーを押して下さい######    

1 1 1 0


【問題4-4】

In [8]:
def OR(x1, x2):
    ######以下にコードを書いて下さい######
    x = np.array([x1, x2])
    w = np.array([0.3, 0.3])
    b = -0.2
    tmp = np.sum(x*w) + b
    if tmp > 0:
        return 1
    else:
        return 0
    
y1 = OR(0, 0)
y2 = OR(0, 1)
y3 = OR(1, 0)
y4 = OR(1, 1)
print(y1, y2, y3, y4)
######「shift + Enter」キーを押して下さい######

0 1 1 1


【問題5-1】

In [9]:
######以下に「XORゲート」のコードを書いて下さい######
def XOR(x1, x2):
    s1 = NAND(x1, x2)
    s2 = OR(x1, x2)
    y = AND(s1, s2)
    
    return y

y1 = XOR(0, 0)
y2 = XOR(0, 1)
y3 = XOR(1, 0)
y4 = XOR(1, 1)
print(y1, y2, y3, y4)
######「shift + Enter」キーを押して下さい######

0 1 1 0


【演習6-1】

In [10]:
import numpy as np

def NOR(x1, x2):
    x = np.array([x1, x2])
    w = np.array([-2.0, -2.0])
    b = 1.0
    tmp = np.sum(x*w) + b
    if tmp > 0:
        return 1
    else:
        return 0
    
y1 = NOR(0, 0)
y2 = NOR(0, 1)
y3 = NOR(1, 0)
y4 = NOR(1, 1)
print(y1, y2, y3, y4)
######「Shift + Enter」を押してください######

1 0 0 0


【演習6-2】

In [11]:
import numpy as np

def XNOR(x1, x2):
    s1 = XOR(x1, x2)
    s2 = XOR(x1, x2)
    y = NOR(s1, s2)
    return y
    
y1 = XNOR(0, 0)
y2 = XNOR(0, 1)
y3 = XNOR(1, 0)
y4 = XNOR(1, 1)
print(y1, y2, y3, y4)

1 0 0 1


「Perceptron-1.ipynb」はここまでになります。

______________________________________

【演習6-3】

In [7]:
import numpy as np
def half_adder(x1, x2):
    ######半加算器を完成させてください######
    c = AND(x1, x2)
    s = XOR(x1, x2)
    
    ######「s」を出力、「c」を桁上げとします#######
    return s, c


print(half_adder(0, 0))
print(half_adder(1, 0))
print(half_adder(0, 1))
print(half_adder(1, 1))
######「shift + Enter」キーを押して下さい######

(0, 0)
(1, 0)
(1, 0)
(0, 1)


【演習6-4】

In [10]:
import numpy as np
def full_adder(x1, x2, Cin):
    ######全加算器を完成させてください######
    s1, c1 = half_adder(x1, x2)
    s2, c2 = half_adder(s1, Cin)
    Cout = OR(c1, c2)
    
    ######「s2」を出力、「Cout」を桁上げとします######
    return s2, Cout

print(full_adder(0, 0, 0))
print(full_adder(0, 0, 1))
print(full_adder(0, 1, 0))
print(full_adder(1, 0, 0))
print(full_adder(0, 1, 1))
print(full_adder(1, 0, 1))
print(full_adder(1, 1, 0))
print(full_adder(1, 1, 1))
######「shift + Enter」キーを押して下さい######

(0, 0)
(1, 0)
(1, 0)
(1, 0)
(0, 1)
(0, 1)
(0, 1)
(1, 1)


【演習6-5】複数パターンがあるので、参考に三つ載せておきます。
一つ目のコードが一番基本的になると思うので、こちらのみ理解してもらえれば大丈夫です。

他のコードは興味ある場合は参考にしてみてください。

In [18]:
######入力部を書き直す必要があるコードPart１######
######しかし一番単純であり見やすい######

######A1,A2,A3は「１０１」といった一つの数字、B1,B2,B3は「１０１」といった一つの数字######
def three_adder(A1, A2, A3, B1, B2, B3):
    s1, c1 = full_adder(A1, B1, 0)
    s2, c2 = full_adder(A2, B2, c1)
    s3, c3 = full_adder(A3, B3, c2)
    if c3 == 1:
        ######文字列の場合と配列の場合の２パターン表記######
        print(str(c3)+str(s3)+str(s2)+str(s1))
        C = np.array([c3, s3, s2, s1])
        print(C)
    elif c3 == 0:
        print(str(s3)+str(s2)+str(s1))
        C = np.array([s3, s2, s1])
        print(C)
        
three_adder(1, 0, 1, 1, 0, 1)

1010
[1 0 1 0]


In [12]:
######入力部を書き直す必要があるコードPart２######

def three_adder(x1, x2):
    z = 0
    t = 0
    y = np.zeros(3)
    for i, j in zip(x1, x2):
        s, c = full_adder(i, j, z)
        z = c
        y[t] = s
        if (t == 2) and (c == 1):
            y = np.append(y, c)
        t += 1
      
    print("１番右を１桁目として表示します。")
    print(np.flipud(y))

######「０番目」から「１桁目」として代入していきます。######
######他の数を計算したいときは以下を書き換えてください。######
x1 = np.array([1, 0, 1])
x2 = np.array([1, 0, 1])
three_adder(x1, x2)

１番右を１桁目として表示します。
[1. 0. 1. 0.]


In [16]:
######「input関数」を用いて上のコードよりかは柔軟性のあるコード######

def three_adder(Cin_zero):
    z = Cin_zero
    y = np.zeros(3)
    for i in range(0, 3):
        x1 = int(input(str(i+1) + "桁目を入力してください："))
        x2 = int(input("もう１つの" + str(i+1) + "桁目を入力してください："))
        s, c = full_adder(x1, x2, z)
        z = c
        y[i] = s
        if (i == 2) and (c == 1):
            y = np.append(y, c)

    print("１番右を１桁目として表示します。")        
    y = np.flipud(y)
    print(y)
######「Cin_zero」は「桁上がりがない」とい意味で用いているので「０」を代入します###### 
######「Reason：当たり前のように０桁目はなく、強いて言うなら０＋０だから」######
three_adder(0)

1桁目を入力してください： 1
もう１つの1桁目を入力してください： 1
2桁目を入力してください： 0
もう１つの2桁目を入力してください： 0
3桁目を入力してください： 1
もう１つの3桁目を入力してください： 1


１番右を１桁目として表示します。
[1. 0. 1. 0.]
